import json
import re

def find_closing_brace_index(text):
    """Finds the index of the closing brace that matches the first opening brace."""
    count = 0
    for i, char in enumerate(text):
        if char == '{':
            count += 1
        elif char == '}':
            count -= 1
            if count == 0:
                return i
    raise ValueError("Unbalanced curly braces")

def parse_output_string(output_string):
    """Parses the output string generated by the AI model into a dictionary."""
    data = {}
    patterns = {
        'short_analysis': r'\*\*Short analysis\*\*: (.+?)\n',
        'commit_title': r'\*\*New Commit Title\*\*: (.+?)\n',
        'detailed_commit_message': r'\*\*New Detailed Commit Message\*\*:\n(.+?)\n\n\*\*Code Changes\*\*:',
        'code_changes': r'\*\*Code Changes\*\*:\n```\n(\{.+\})\n```'
    }

    for key, pattern in patterns.items():
        match = re.search(pattern, output_string, re.DOTALL)
        if match:
            if key == 'code_changes':
                data[key] = json.loads(match.group(1))
            else:
                data[key] = match.group(1).strip()

    return data